services:
  frontend:
    image: hello-frontend:latest
    ports:
      - "5001:5001"
  backend:
    image: hello-backend:latest
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db_container
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    ports:
      - "8080:8080"
  redis:
    image: redis:latest
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    container_name: db_container
    volumes:
      - ./database:/var/lib/postgresql
  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf